'use client'
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { AppProvider } from "@/context/AppProvider";
import { useThemeStore } from "@/store/themeStore";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { theme, setTheme } = useThemeStore();
  return (
    <html lang="en">
      <body
        style={inter.style}
        className={`
        w-full h-screen bg-cover bg-no-repeat bg-center bg-fixed relative flex justify-center items-start mt-32
        ${
          theme === "light"
            ? 'bg-[url("/theme/light.jpeg")]'
            : 'bg-[url("/auth/imgAuth.jpeg")]'
        }
        `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
